import { CustomerQuotationDetails } from './CustomerQuotationDetails';

export interface CustomerQuotation {
customerQuotationQid?:number,
customerQuotationQuotationId?:string,
customerQuotationQuotationAddition?:number,
customerQuotationQuotationRoot?:number,
customerQuotationQuotationDate?:Date,
customerQuotationQuotationValidDate?:Date,
customerQuotationCustomerId?:number,
customerQuotationEnquiryId?:number,
customerQuotationRemarks?:string,
customerQuotationLocationId?:number,
customerQuotationDiscountPercentage?:number,
customerQuotationDiscountAmount?:number
customerQuotationGrossTotal?:number,
customerQuotationNetTotal?:number,
customerQuotationSalesManId?:number,
customerQuotationCurrencyId?:number,
customerQuotationSubject?:string,
customerQuotationNote?:string,
customerQuotationWarranty?:string,
customerQuotationTraining?:string,
customerQuotationTechnicalDetails?:string,
customerQuotationTerms?:string,
customerQuotationDeliveryTimeDate?:Date,
customerQuotationPacking?:string,
customerQuotationQuality ?:string,
customerQuotationHeader?:string,
customerQuotationFooter?:string,
customerQuotationQuotationStatusId?:number,
customerQuotationFsno?:number,
customerQuotationIsClose?:Boolean,
customerQuotationEnquiryNo ?:string,
customerQuotationVoucherType?:string,
customerQuotationCashCustomerName?:string,
customerQuotationContactPersonV?:string,
customerQuotationDiscountAmountTotal?:number,
customerQuotationVendorId?:number,
customerQuotationTypeId?:number,
customerQuotationModelId?:number,
customerQuotationVatPercentage?:number,
customerQuotationVatAmount?:number,
customerQuotationQuotationEnquiryN?:number,
CustomerQuotationDetails: CustomerQuotationDetails[],
customerQuotationDelStatus?:Boolean
}