export interface CustomerMaster{
    CustomerMasterCustomerNo?: number;
    CustomerMasterCustomerTitle?: string;
    CustomerMasterCustomerName?: string;
    CustomerMasterCustomerType?: string;
    CustomerMasterCustomerContactPerson?: string;
    CustomerMasterCustomerCountryId?: number;
    CustomerMasterCustomerCityId?: number;
    CustomerMasterCustomerPoBox?: string;
    CustomerMasterCustomerTel1?: string;
    CustomerMasterCustomerTel2?: string;
    CustomerMasterCustomerMobile?: string;
    CustomerMasterCustomerFax?: string;
    CustomerMasterCustomerEmail?:string;
    CustomerMasterCustomerWebSite?: string;
    CustomerMasterCustomerLocation?: string;
    CustomerMasterCustomerRemarks?: string;
    CustomerMasterCustomerReffAcNo?: string;
    CustomerMasterCustomerUserId?:number;
    CustomerMasterCustomerCurrencyId?: number;
    CustomerMasterCustomerCreditLimit?: number;
    CustomerMasterCustomerCreditDays?: number;
    CustomerMasterCustomerBlackList?: boolean;
    CustomerMasterCustomerStatus?:number;
    CustomerMasterCustomerDeleteStatus?: boolean;
    CustomerMasterCustomerJoinDate?: Date;
    CustomerMasterCustomerStatusValue?: boolean;
    CustomerMasterCustomerCreateAccount?: boolean;
    CustomerMasterCustomerPriceLevel?: string;
    CustomerMasterCustomerPriceLevelId?: number;
    CustomerMasterCustomerCustType?: string;
    CustomerMasterCustomerContactPerson2?: string;
    CustomerMasterCustomerContactPerson3?: string;
    CustomerMasterCustomerVatNo?: string;
    CustomerMasterCustomerLoyaltyId?: number;
    CustomerMasterCustomerEarnPoints?: number;
    CustomerMasterCustomerTotalPoints?: number;
    CustomerMasterCustomerTotalValue?: number;
    CustomerMasterCustomerRedeemEarnPoints?: number;
    CustomerMasterCustomerArabicName?: string;
    CustomerMasterCustomerGroupAccNo?: string;
    CustomerMasterCustomerCtTypeId?: number;
}